server:
  port: 8000
  servlet:
    contextPath: /api

spring:
  application:
    name: boiler-plate
  datasource:
    url: jdbc:mariadb://localhost:43306/boilerplate?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    open-in-view: false
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
    password: ""
  data:
    redis:
      repositories:
        enabled: false

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, metrics, circuitbreakers

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
jwt:
  header: Authorization
  secret: secret
  access-token-validity-in-seconds: 3600 # 10 min

custom:
  slack-channel: slack-incomming-webhook-url

sentry:
  dsn: sentry ????
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
