server:
  port: 8000

spring:
  application:
    name: boiler-plate
  datasource:
    url: jdbc:mariadb://localhost:43306/boilerplate_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    open-in-view: false
  config:
    activate:
      on-profile: test
  redis:
    host: localhost
    port: 6379
    password: ""
  data:
    redis:
      repositories:
        enabled: false
jwt:
  header: Authorization
  secret: secret
  access-token-validity-in-seconds: 3600 # 10 min

custom:
  slack-channel:
# ?? ?? ?? ??? ??? ?? ????? ?? ????
#logging:
#  level:
#    org:
#      springframework.jdbc.core: trace
#      hibernate:
#        type: trace
